gener:
	protoc --go_out=../../gen/go --go_opt=paths=source_relative --go-grpc_out=../../gen/go --go-grpc_opt=paths=source_relative sso.proto
	#protoc --go_out=squarer --go_opt=paths=source_relative --go-grpc_out=squarer --go-grpc_opt=paths=source_relative ./proto/hello.proto
